PROGRAM WWW_FCODE_CN
    IMPLICIT NONE

    INTEGER ::I
    INTEGER,DIMENSION(5):: ARR
    DATA ARR/1, 2, 5, 4, 3/

    WRITE(*,'(A,3X,A)')'INDEX','VALUE'
    DO I=1,5
        WRITE(*,'(2I5)')I,ARR(I)
    ENDDO

    PRINT *
    WRITE(*,'(A,1X,A)')'MAX_LOC','MAX_VAL'
    WRITE(*,'(2I5)')MAXLOC(ARR),MAXVAL(ARR)

    PRINT *,"PROGRAM TERMINATED"
    STOP

END PROGRAM WWW_FCODE_CN
