SUBROUTINE SWAP(AUTOARR1,AUTOARR2,N)
    IMPLICIT NONE
    INTEGER:: N
    REAL,DIMENSION(N) :: AUTOARR1,AUTOARR2
    REAL,ALLOCATABLE,DIMENSION(:)::DYNARR

    ALLOCATE(DYNARR(N))
    DYNARR(:N)=AUTOARR1(:N)
    AUTOARR1(:N)=AUTOARR2(:N)
    AUTOARR2(:N)=DYNARR(:N)
    DEALLOCATE(DYNARR)

END SUBROUTINE SWAP

PROGRAM WWW_FCODE_CN
    IMPLICIT NONE

    INTEGER,PARAMETER:: NARR=5
    REAL,PARAMETER:: PI=3.14159265
    REAL,DIMENSION(NARR):: FIXARR1,FIXARR2
    INTEGER::I

!  ASSIGN
    FIXARR1(:NARR)=(/(SIN(PI*(I-1.)/(NARR-1)),I=1,NARR)/)
!  ASSIGN,FUNCTION ARG
    FIXARR2(:NARR)=COS( (/(PI*(I-1.)/(NARR-1),I=1,NARR)/) )

    WRITE(*,*)"BEFORE SWAP..."
    WRITE(*,'(7F12.6)')FIXARR1(:NARR)
    WRITE(*,'(7F12.6)')FIXARR2(:NARR)

    CALL SWAP(FIXARR1,FIXARR2,NARR)

    WRITE(*,*)"AFTER SWAP..."
    WRITE(*,'(7F12.6)')FIXARR1(:NARR)
    WRITE(*,'(7F12.6)')FIXARR2(:NARR)

    STOP

END PROGRAM WWW_FCODE_CN
