MODULE STUDENTCLASS
    TYPE STUDENT
        INTEGER :: ID
        CHARACTER(LEN=100)::NAME
        INTEGER:: CHINESESCO,MATHSCO,ENGLISHSCO
    CONTAINS
        PROCEDURE :: PRINT_STUDENT_INFORTMATION => PRINT_STUDENT_INFORTMATION
    END TYPE STUDENT
CONTAINS
    SUBROUTINE PRINT_STUDENT_INFORTMATION(THIS)
        CLASS (STUDENT) :: THIS
        WRITE(*,*)'STUDENT INFOR:'
        WRITE(*,*)"NAME:         ",THIS%NAME
        WRITE(*,*)"STUDENT NO.:  ",THIS%ID
        WRITE(*,*)"CHINESE SCORE:",THIS%CHINESESCO
        WRITE(*,*)"MATH SCORE:   ",THIS%MATHSCO
        WRITE(*,*)"ENGLISH SCORE:",THIS%ENGLISHSCO
    END SUBROUTINE PRINT_STUDENT_INFORTMATION
END MODULE STUDENTCLASS

PROGRAM WWW_FCODE_CN
    USE STUDENTCLASS
    IMPLICIT NONE

    TYPE (STUDENT):: FLYBIRD

    FLYBIRD=STUDENT(2,"FLYBIRD",60,97,17)
    CALL FLYBIRD%PRINT_STUDENT_INFORTMATION()


    PRINT *,"PROGRAM TERMINATED"
    STOP

END PROGRAM WWW_FCODE_CN
