PROGRAM WWW_FCODE_CN
    IMPLICIT NONE

    TYPE :: STUDENT
        INTEGER :: ID
        CHARACTER(LEN=100)::NAME
        INTEGER:: CHINESESCO,MATHSCO,ENGLISHSCO
    END TYPE

    TYPE (STUDENT):: FLYBIRD
    FLYBIRD%ID = 001
    FLYBIRD%NAME = "FLYBIRD"
    FLYBIRD%CHINESESCO = 60
    FLYBIRD%MATHSCO = 97
    FLYBIRD%ENGLISHSCO = 17

    WRITE(*,*)'STUDENT INFOR:'
    WRITE(*,*)"NAME:         ",FLYBIRD%NAME
    WRITE(*,*)"STUDENT NO.:  ",FLYBIRD%ID
    WRITE(*,*)"CHINESE SCORE:",FLYBIRD%CHINESESCO
    WRITE(*,*)"MATH SCORE:   ",FLYBIRD%MATHSCO
    WRITE(*,*)"ENGLISH SCORE:",FLYBIRD%ENGLISHSCO

    PRINT *,"PROGRAM TERMINATED"
    STOP

END PROGRAM WWW_FCODE_CN
