PROGRAM WWW_FCODE_CN
    IMPLICIT NONE

    TYPE EMPLOYEE_NAME
        CHARACTER(LEN=25):: LAST_NAME
        CHARACTER(LEN=15):: FIRST_NAME
    END TYPE
    TYPE EMPLOYEE_ADDR
        CHARACTER(LEN=20):: STREET_NAME
        INTEGER(KIND=2)  :: STREET_NUMBER
        INTEGER(KIND=2)  :: APT_NUMBER
        CHARACTER(LEN=20):: CITY
        CHARACTER(LEN=2) :: STATE
        INTEGER(KIND=8)  :: ZIP
    END TYPE
    TYPE EMPLOYEE_DATA
        TYPE (EMPLOYEE_NAME):: NAME
        TYPE (EMPLOYEE_ADDR):: ADDR
        INTEGER(KIND=4)     :: TELEPHONE
        INTEGER(KIND=2)     :: DATE_OF_BIRTH
        INTEGER(KIND=2)     :: DATE_OF_HIRE
        INTEGER(KIND=2)     :: SOCIAL_SECURITY(3)
        LOGICAL(KIND=2)     :: MARRIED
        INTEGER(KIND=2)     :: DEPENDENTS
    END TYPE

    TYPE (EMPLOYEE_DATA), DIMENSION (20) :: EMPLOYEES

    DATA EMPLOYEES(1)%NAME /EMPLOYEE_NAME("BIRD","FLY")/

    EMPLOYEES(2)=EMPLOYEE_DATA(  EMPLOYEE_NAME("BIRD","FLY"),                      &
                                 EMPLOYEE_ADDR("ZGC",12,34,"BEIJING","BJ",100000), &
                                 10086,04,15,(/0,0,0/),.TRUE.,0                    &
                                 )

    PRINT *,EMPLOYEES(1)%NAME%FIRST_NAME,EMPLOYEES(1)%NAME%LAST_NAME
    PRINT *,EMPLOYEES(2)%NAME%FIRST_NAME,EMPLOYEES(2)%NAME%LAST_NAME
    STOP

END PROGRAM WWW_FCODE_CN
